### ISSUE TITLE
Eigen 

### ISSUE THREAD

**Issue by nddk** [clab/cnn#37]
Hi, 

when using a large hidden state size for the LSTM, it runs a bit slow. Are there any recommended settings for Eigen? e.g., using multithreading or linking with intel MKL?  

Also, is there an option to use double instead of float for all Parameters?

**Comment by neubig** [comment]
Linking with the Intel MKL is a good idea if it's possible. I've never tried this, so if you get it working, contributing a recipe would be great. Multi-threading and full GPU support are currently in progress, and will be noted in https://github.com/clab/cnn/issues/28 when it's completed.
