### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [clab/cnn#42]
Would you like to [replace any double quotes](https://github.com/clab/cnn/blob/7b8adbc9738250922436293e1e0873754c290eab/cnn/cfsm-builder.h#L6 "Check header file inclusion style") by [angle brackets around file names for include statements](http://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by neubig** [comment]
Sure, feel free to submit a pull request that does so!
