### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [clab/cnn#43]
I would like to point out that an identifier like "[`_TIMING_H_`](https://github.com/clab/cnn/blob/7b8adbc9738250922436293e1e0873754c290eab/cnn/timing.h#L1)" [does not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by neubig** [comment]
Sure, feel free to submit a pull request that does so!
