### ISSUE TITLE
problem with boost while performing 'make'

### ISSUE THREAD

**Issue by lavelli** [clab/cnn#50]
A follow-up of a discussion on Linkedin concerning BIST Parser. I'm aware this is not a pyCNN specific issue but searching on internet I was not able to find a solution.

When installing pyCNN (as specified in https://github.com/clab/cnn/blob/master/INSTALL.md), I encounter a problem when I perform 'make' (after customizing setup.py). Even if the previous steps seem ok, when I run ' make', an error is issued:

> make
cp ../build/cnn/libcnn_shared.so .
python setup.py build_ext --inplace
running build_ext
skipping 'pycnn.cpp' Cython extension (up-to-date)
building 'pycnn' extension
/usr/bin/gcc-4.9 -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/home/lavelli/cnn -I/home/lavelli/eigen-eigen-774d70b529d6 -I/usr/include/python2.7 -c pycnn.cpp -o build/temp.linux-x86_64-2.7/pycnn.o -std=c++11
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
In file included from pycnn.cpp:257:0:
/home/lavelli/cnn/cnn/tensor.h:16:41: fatal error: boost/serialization/array.hpp: No such file or directory
#include <boost/serialization/array.hpp>
^
compilation terminated.
error: command '/usr/bin/gcc-4.9' failed with exit status 1
make: *** [pycnn.so] Error 1

Note that I have installed boost_1_60_0 under my home directory (I also created a link named 'boost' to boost_1_60_0). and the file array.hpp exists both under $HOME/boost/boost/serialization/ and $HOME/boost/include/boost/serialization/.

Thanks in advance

**Comment by olsgaard** [comment]
I too had a lot of problems with installing pyCNN and found most the errors I received of little help, so I unfortunately can't pinpoint the problem you are experiencing. Here are some notes I wrote down when I installed on OSX, hope they can be of help to you:

* The PyCNN install guide recommends latest stable version of Eigen, the README file for CNN recommends latest development build. You might have to try both. Either can be installed from http://eigen.tuxfamily.org/ (just unzip and move to cnn folder and rename to eigen and you don’t have to mess with mercury/hg)
* The PyCNN install guide hints that you should use python 2.x. This is not a hint **Python 2.7 is required** for PyCNN
* You can add extra compiler flags in setup.py. On OSX you may need to include the following extra_compile_args(remember the trailing comma. These are function arguments!):
`[‘-mmacosx-version-min=10.7′,’-std=c++11′,’-stdlib=libc++’]`,

* You might need to do things several times. Be patient and be stubborn!

**Comment by neubig** [comment]
Hi @lavelli sorry I missed this. Were you able to compile CNN itself (not PyCNN) properly according to the instructions in the main README.md? If not, try adding the following arguments when you run the cmake command:

`-DBOOST_ROOT:PATHNAME=$HOME/boost_1_60_0 -DBoost_LIBRARY_DIRS:FILEPATH=$HOME/boost_1_60_0/lib`

**Comment by olsgaard** [comment]
I've been having problems installing pyCNN on Ubuntu 12.10. Adding those arguments made cmake, when building CNN, look for boost in a completely different folder (`/usr/include/` where the default 1.49 version is, instead of in the home directory where I have compiled newer versions)

If I run the cmake command as in the README.md it works, but I get an error when running `make -j 2`.

* With boost 1.49 I get error at the 73% mark
* With boost 1.58 I get error at the 92% mark
* With boost 1.60 I get error at the 93% mark

There is a little over 100 fairly incomprehensible error messages. Below are a few from compiling with boost 1.60:

    ...
    rINS_15program_options16validation_errorEEE]+0x30): undefined reference to `boost::program_options:
    ...
    MakeFiles/segrnn-sup.dir/segrnn-sup.cc.o:(.data.rel.ro._ZTVN5boost16exception_detail19error_njectorINS_15program_options20invalid_option_valueEEE[_ZTVN5boost16exception_detail19error_inectorINS_15program_options20invalid_option_valueEEE]+0x30): undefined reference to `boost::proptions::error_with_option_name::substitute_placeholders(std::string const&) const'
    ...
    CMakeFiles/segrnn-sup.dir/segrnn-sup.cc.o:(.data.rel.ro._ZTVN5boost16exception_detail10clone_S0_19error_info_injectorINS_15program_options20invalid_option_valueEEEEE[_ZTVN5boost16exceptiail10clone_implINS0_19error_info_injectorINS_15program_options20invalid_option_valueEEEEE]+0xndefined reference to `boost::program_options::error_with_option_name::substitute_placeholder:string const&) const'
    collect2: error: ld returned 1 exit status
    make[2]: *** [examples/segrnn-sup] Error 1
    make[1]: *** [examples/CMakeFiles/segrnn-sup.dir/all] Error 2
    make[1]: *** Waiting for unfinished jobs....
    /home/mads/cnn/examples/tok-embed.cc: In function ‘int main(int, char**)’:
    /home/mads/cnn/examples/tok-embed.cc:267:7: warning: unused variable ‘report’ [-Wunused-varia
    Linking CXX executable tok-embed
    [ 93%] Built target tok-embed
    make: *** [all] Error 2
   
(I've replaced numerous lines with `...` above)

**Comment by neubig** [comment]
Hmm, could you additionally add: `-DBoost_NO_BOOST_CMAKE=TRUE -DBoost_NO_SYSTEM_PATHS=TRUE` and see if this makes any difference?

**Comment by olsgaard** [comment]
Thank you for your quick response.

Adding `-DBoost_NO_SYSTEM_PATHS=TRUE` helped and made CNN compile without errors. After that I ran `make` and `make install` in the pycnn folder and added `export LD_LIBRARY_PATH=/home/mads/cnn/pycnn` to my environment in accordance with `INSTALL.md`, without any errors. However, importing pyCNN in python fails.

    pyexamples/$ python xor.py
    Traceback (most recent call last):
      File "xor.py", line 1, in <module>
        from pycnn import *
      File "build/bdist.linux-x86_64/egg/pycnn.py", line 7, in <module>
      File "build/bdist.linux-x86_64/egg/pycnn.py", line 6, in __bootstrap__
    ImportError: libboost_serialization.so.1.60.0: cannot open shared object file: No such file or directory

**Comment by neubig** [comment]
OK, you'll also need to add the location of the boost libraries to your LD_LIBRARY_PATH:
`export LD_LIBRARY_PATH=/home/mads/cnn/pycnn:/path/to/boost/lib`

**Comment by olsgaard** [comment]
When you mention it, it makes perfect sense. Thank you very much for your help, it did the trick!

**Comment by neubig** [comment]
Great! Instructions noting such have been added to README.md in the v2 branch.
