### ISSUE TITLE
--cnn-mem How to do this?

### ISSUE THREAD

**Issue by berzentine** [clab/cnn#52]
How to allocate more memory to cnn. There is an error that it ran out of memory each time.

**Comment by neubig** [comment]
When you have a program compiled with cnn, and assuming that you call cnn's Initialize() function using the command line arguments passed in to the program, it's as simple as adding:
$ my_program --cnn-mem 1024 [other options]
to your command line arguments. Note that the cnn arguments must come before any other arguments.

These command line arguments should be documented, so I'll leave this issue open and add this to the documentation when I have a chance.

**Comment by yoavg** [comment]
A small addition to this: we observe that setting --cnn-mem to values above 2010 or so always fail. Probably relates to some limits on contiguous memory allocation.

**Comment by Oneplus** [comment]
@yoavg @neubig it seems the current master has an integer overflow problem on the devices.cc when allocating memory. See this bug fixed in v2 (https://github.com/clab/cnn/blob/v2/cnn/devices.cc#L63) but not sure when will it be merged into master.

**Comment by yoavg** [comment]
Thanks! is v2 operational already?

**Comment by neubig** [comment]
Yes, it's basically operational. I've switched my experiments over to v2. There are still a few things that need to be done, but I think we'll be merging it into master sooner rather than later.

**Comment by neubig** [comment]
Information about command line options has been added to README.md

**Comment by esalesky** [comment]
It seems to be the case that the order of the cnn args also matters. I'm using v2 and seeing that the --cnn-mem arg is ignored unless preceded by cnn-gpus or cnn-gpu-ids; it'll just use 512. Can see with the example:

```
./examples/xor --cnn-mem 1024
[cnn] allocating memory: 512MB

./examples/xor --cnn-mem 1024 --cnn-gpu-ids 3
[cnn] allocating memory: 512MB

./examples/xor --cnn-gpu-ids 3 --cnn-mem 1024
[cnn] allocating memory: 1024MB

./examples/xor --cnn-gpus 1 --cnn-mem 1024
[cnn] allocating memory: 1024MB
```

**Comment by esalesky** [comment]
It seems to be the case that the order of the cnn args also matters. I'm using v2 and seeing that the --cnn-mem arg is ignored unless preceded by cnn-gpus or cnn-gpu-ids (will use 512 default) and those two args will fail if they follow cnn-mem. Can see with the xor example:

```
./examples/xor --cnn-mem 1024
[cnn] allocating memory: 512MB

./examples/xor --cnn-mem 1024 --cnn-gpu-ids 3
[cnn] Device(s) selected: 2
[cnn] Bad command line argument: --cnn-gpu-ids
Aborted (core dumped)

./examples/xor --cnn-gpu-ids 3 --cnn-mem 1024
[cnn] allocating memory: 1024MB

./examples/xor --cnn-gpus 1 --cnn-mem 1024
[cnn] allocating memory: 1024MB
```
