### ISSUE TITLE
CPU you selected does not support x86-64 instruction set

### ISSUE THREAD

**Issue by riyazbhat** [clab/cnn#65]
I have the following CPU config;
lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                6
.
.
.

But when I try to make ``cnn``, i get  an error message saying ``CPU you selected does not support x86-64 instruction set``. 

Here is the complete error log:
make VERBOSE=1
/usr/local/bin/cmake -H/home/riyaz/GIT_Projects/cNN/cnn -B/home/riyaz/GIT_Projects/cNN/cnn/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/bin/cmake -E cmake_progress_start /home/riyaz/GIT_Projects/cNN/cnn/build/CMakeFiles /home/riyaz/GIT_Projects/cNN/cnn/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory `/home/riyaz/GIT_Projects/cNN/cnn/build'
make -f cnn/CMakeFiles/cnn.dir/build.make cnn/CMakeFiles/cnn.dir/depend
make[2]: Entering directory `/home/riyaz/GIT_Projects/cNN/cnn/build'
cd /home/riyaz/GIT_Projects/cNN/cnn/build && /usr/local/bin/cmake -E cmake_depends "Unix Makefiles" /home/riyaz/GIT_Projects/cNN/cnn /home/riyaz/GIT_Projects/cNN/cnn/cnn /home/riyaz/GIT_Projects/cNN/cnn/build /home/riyaz/GIT_Projects/cNN/cnn/build/cnn /home/riyaz/GIT_Projects/cNN/cnn/build/cnn/CMakeFiles/cnn.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/home/riyaz/GIT_Projects/cNN/cnn/build'
make -f cnn/CMakeFiles/cnn.dir/build.make cnn/CMakeFiles/cnn.dir/build
make[2]: Entering directory `/home/riyaz/GIT_Projects/cNN/cnn/build'
/usr/local/bin/cmake -E cmake_progress_report /home/riyaz/GIT_Projects/cNN/cnn/build/CMakeFiles 1
[  3%] Building CXX object cnn/CMakeFiles/cnn.dir/cfsm-builder.cc.o
cd /home/riyaz/GIT_Projects/cNN/cnn/build/cnn && /usr/bin/c++    -fPIC -funroll-loops -Wall -std=c++11 -Ofast -g -DEIGEN_FAST_MATH -march=native -I/home/riyaz/GIT_Projects/cNN/cnn -I/home/riyaz/GIT_Projects/cNN/cnn/external/easyloggingpp/src -I/usr/local/include -I/home/riyaz/GIT_Projects/cNN/cnn/../eigen -I/home/riyaz/GIT_Projects/cNN/cnn/build    -o CMakeFiles/cnn.dir/cfsm-builder.cc.o -c /home/riyaz/GIT_Projects/cNN/cnn/cnn/cfsm-builder.cc
/home/riyaz/GIT_Projects/cNN/cnn/cnn/cfsm-builder.cc:1:0: error: CPU you selected does not support x86-64 instruction set
make[2]: *** [cnn/CMakeFiles/cnn.dir/cfsm-builder.cc.o] Error 1
make[2]: Leaving directory `/home/riyaz/GIT_Projects/cNN/cnn/build'
make[1]: *** [cnn/CMakeFiles/cnn.dir/all] Error 2
make[1]: Leaving directory `/home/riyaz/GIT_Projects/cNN/cnn/build'
make: *** [all] Error 2

**Comment by neubig** [comment]
Thanks for the issue report! Unfortunately I've never encountered this, and unless we can reproduce it it will be hard for us to debug. If you figure out a fix to the problem we'd be happy to incorporate a pull request though.
