### ISSUE TITLE
Problems when update lookup parameters in parent process

### ISSUE THREAD

**Issue by Adoni** [clab/cnn#67]
I try to use `sgd->update()` in parent process to update lookup parameters. However, it doesn't work. When I use `sgd->update()` in child process, it works well. This problem is caused by that the variable `non_zero_grads` in model is not shared. So parent process will not update lookup parameters because this variable is empty.

**Comment by neubig** [comment]
Hi @Adoni , thanks for the bug report. Are you talking about when you're using the multi-process framework (included in the `mp.h` file)? Could you attach some minimal example code so we can take a look at it?

**Comment by Adoni** [comment]
Hi @neubig, I didn't use the `mp.h` file, which is update in child process. My work cannot use this file directly so I write a multi-process program, which update in parent process. I will try to write a minimal example to make it recur.

**Comment by neubig** [comment]
If this is something that you wrote on your own, you'll probably have to fix the problem on your own. This will probably involve passing information about `non_zero_grads` in each child process to the parent process. If you do so, you could combine add all elements of `non_zero_grads` in each child process to `non_zero_grads` in the parent process before running the update. As this is something that we don't officially support as part of cnn, I'm going to close the issue.
