### ISSUE TITLE
overly aggressive nonzero-component assertion

### ISSUE THREAD

**Issue by dhgarrette** [clab/cnn#68]
In `model.h`, `LookupParameterStorage` contains the [following field](https://github.com/clab/cnn/blob/v2/cnn/model.h#L114):

    // gradients are sparse, so track which components are nonzero
    std::unordered_set<unsigned> non_zero_grads;

In `model.cc`, `LookupParameterStorage::g_squared_l2norm_dev` contains the [following assertion](https://github.com/clab/cnn/blob/v2/cnn/model.cc#L342):

    auto it = non_zero_grads.begin();
    assert(it != non_zero_grads.end());

However, this assertion is causing failures under two conditions that seem like they should be valid: 

1. Parameters that are created but not used.  Likely if this happens it is a programming error, but either it should be ignored because it doesn't matter or a more appropriate error message should be displayed.

2. Lookup parameters that are set not to update (using `expr::const_lookup`).  This one definitely should not be throwing errors.

Note: I discovered and tested these using pycnn, but presumably the issues hold for c++ code as well.

**Comment by neubig** [comment]
Sorry this took so long, but this should be fixed here: https://github.com/clab/cnn/commit/de997e01dc585f559bac203e0b1c84ff9b9c1bb9
