### ISSUE TITLE
assertion failure during update if no lookup is performed (v2)

### ISSUE THREAD

**Issue by yoavg** [clab/cnn#89]
When a lookup parameters is added to a model, it must be queried at least once before a model update or code crashes with assertion failure.

the error message:
```
Assertion failed: (it != non_zero_grads.end()), function g_squared_l2norm_dev, file /Users/yogo/V/playwith/cnn_v2/cnn/cnn/model.cc, line 343.
```

code:
```
import pycnn as pc

m = pc.Model()
lp = m.add_lookup_parameters((10, 10))
pb = m.add_parameters(10)

trainer = pc.AdamTrainer(m)

pc.renew_cg()
lp[0] # without this line the code crashes

b = pc.parameter(pb)
e = pc.dot_product(b,b)

e.value()
e.backward()
trainer.update()
```

**Comment by dhgarrette** [comment]
Related to #68 ?

**Comment by yoavg** [comment]
oh, yes, this seem to be the same bug.

I disagree with your assessment that defining a lookup table and not looking up anything is a programmer error though. could be that different lookup tables are used in different sentences (say you are doing some multi-task setup and have per-task tables)

**Comment by redpony** [comment]
It definitely shouldn't be a programmer error. This is a bug. :)

**Comment by neubig** [comment]
Sorry this took so long, but this should be fixed here: https://github.com/clab/cnn/commit/de997e01dc585f559bac203e0b1c84ff9b9c1bb9
